"""Offline expert episodes and shared BC windows; no learner-side task costs."""

import argparse
import json
from dataclasses import dataclass
from pathlib import Path

import numpy as np

from .env import OBS_FIELDS, Context, rollout_expert, sample_context


@dataclass
class Normalizer:
    obs_mean: np.ndarray
    obs_scale: np.ndarray
    action_mean: np.ndarray
    action_scale: float

    @classmethod
    def fit(cls, episodes):
        observations = np.concatenate([ep["observations"] for ep in episodes])
        actions = np.concatenate([ep["actions"] for ep in episodes])
        # A scalar action scale preserves Euclidean contact-frame geometry.
        return cls(observations.mean(axis=0), np.maximum(observations.std(axis=0), .01),
                   actions.mean(axis=0), float(max(np.sqrt(actions.var(axis=0).mean()), .01)))

    def normalize_obs(self, value):
        return ((np.asarray(value) - self.obs_mean) / self.obs_scale).astype(np.float32)

    def denormalize_obs(self, value):
        return np.asarray(value) * self.obs_scale + self.obs_mean

    def normalize_action(self, value):
        return ((np.asarray(value) - self.action_mean) / self.action_scale).astype(np.float32)

    def denormalize_action(self, value):
        return np.asarray(value) * self.action_scale + self.action_mean

    def to_dict(self):
        return dict(obs_mean=self.obs_mean.tolist(), obs_scale=self.obs_scale.tolist(),
                    action_mean=self.action_mean.tolist(), action_scale=self.action_scale)

    @classmethod
    def from_dict(cls, value):
        return cls(np.asarray(value["obs_mean"], dtype=np.float32),
                   np.asarray(value["obs_scale"], dtype=np.float32),
                   np.asarray(value["action_mean"], dtype=np.float32),
                   float(value["action_scale"]))


def _expert_passed(episode):
    """Collection quality check only; never a training loss or selection target."""
    context = Context.from_dict(episode["context"])
    last = episode["observations"][-1]
    infos = episode["infos"]
    tail = int(np.ceil(.5 / context.physics.control_dt))
    return bool(abs(context.tangent @ last[:2] - context.goal) < .025
                and np.linalg.norm(last[2:4]) < .08
                and np.mean(infos["contact"][-tail:]) >= .9
                and np.max(infos["peak_penetration"]) <= .02
                and np.max(infos["peak_normal_force"]) <= 30.)


def make_dataset(output, train_episodes=128, val_episodes=16, test_episodes=16, seed=0):
    """Write one immutable collection. Episodes, not windows, define splits.

    OOD geometry/physics and impulses are generated by evaluation, never mixed
    into this collection. Failed expert episodes are reported, not filtered.
    """
    output = Path(output)
    if train_episodes < 1 or min(val_episodes, test_episodes) < 0:
        raise ValueError("Need at least one training episode and nonnegative split sizes.")
    if output.exists():
        raise FileExistsError(f"Dataset output already exists: {output}")
    if max(train_episodes, val_episodes, test_episodes) >= 1_000_000:
        raise ValueError("Use fewer than one million episodes per split.")
    output.mkdir(parents=True)
    arrays, entries, training = {}, [], []
    for split_index, (split, count) in enumerate(
            (("train", train_episodes), ("val", val_episodes), ("test", test_episodes))):
        for index in range(count):
            episode_seed = int(seed + split_index * 1_000_000 + index)
            episode = rollout_expert(sample_context(episode_seed))
            episode_id = f"{split}_{index:06d}"
            arrays[f"{episode_id}/observations"] = episode["observations"]
            arrays[f"{episode_id}/actions"] = episode["actions"]
            for name, value in episode["infos"].items():
                arrays[f"{episode_id}/infos/{name}"] = value
            entries.append(dict(id=episode_id, split=split, seed=episode_seed,
                                context=episode["context"], length=len(episode["actions"]),
                                expert_passed=_expert_passed(episode)))
            if split == "train":
                training.append(episode)
    normalizer = Normalizer.fit(training)
    np.savez_compressed(output / "episodes.npz", **arrays)
    failed = sum(not entry["expert_passed"] for entry in entries)
    manifest = dict(schema_version=1, seed=seed, observation_fields=list(OBS_FIELDS),
                    action_profile="absolute_cartesian_target_2d",
                    split_counts=dict(train=train_episodes, val=val_episodes, test=test_episodes),
                    expert_quality=dict(passed=len(entries) - failed, failed=failed, filtered=0),
                    normalizer=normalizer.to_dict(), episodes=entries)
    (output / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    if failed:
        raise RuntimeError(f"{failed} expert episodes failed quality checks; see {output}/manifest.json")
    return manifest


def load_episodes(root, split="train"):
    root = Path(root)
    manifest = json.loads((root / "manifest.json").read_text())
    entries = [entry for entry in manifest["episodes"] if entry["split"] == split]
    if split not in manifest["split_counts"]:
        raise ValueError(f"Unknown dataset split: {split}")
    episodes = []
    with np.load(root / "episodes.npz", allow_pickle=False) as archive:
        for entry in entries:
            prefix = entry["id"]
            info_prefix = f"{prefix}/infos/"
            episodes.append(dict(id=prefix, context=entry["context"],
                                 observations=archive[f"{prefix}/observations"],
                                 actions=archive[f"{prefix}/actions"],
                                 infos={key[len(info_prefix):]: archive[key]
                                        for key in archive.files if key.startswith(info_prefix)}))
    return episodes


def load_normalizer(root):
    return Normalizer.from_dict(json.loads((Path(root) / "manifest.json").read_text())["normalizer"])


class EpisodeWindows:
    """History includes current observation and only strictly previous actions.

    Initial observations repeat the reset observation; unavailable past targets
    equal the initial physical position. Final future chunks repeat the final
    target, never reading another episode. ``limit`` selects training episodes
    and their normalization statistics, even when requesting validation windows.
    Validation/test episodes themselves are never truncated by that argument.
    """

    def __init__(self, root, split="train", obs_history=2, action_history=2, horizon=8, limit=None):
        if min(obs_history, action_history, horizon) < 1:
            raise ValueError("History lengths and horizon must be positive.")
        if limit is not None and limit < 1:
            raise ValueError("Training episode limit must be positive.")
        training = load_episodes(root, "train")
        if limit is not None:
            if limit > len(training):
                raise ValueError(f"Requested {limit} demos, but dataset has {len(training)}.")
            training = training[:limit]
        self.episodes = training if split == "train" else load_episodes(root, split)
        self.normalizer = Normalizer.fit(training)
        self.obs_history, self.action_history, self.horizon = obs_history, action_history, horizon
        self.indices = [(episode_index, step) for episode_index, episode in enumerate(self.episodes)
                        for step in range(len(episode["actions"]))]

    def __len__(self):
        return len(self.indices)

    def __getitem__(self, index):
        episode_index, step = self.indices[index]
        episode = self.episodes[episode_index]
        actions, observations = episode["actions"], episode["observations"]
        observation_indices = np.maximum(np.arange(step - self.obs_history + 1, step + 1), 0)
        action_indices = np.arange(step - self.action_history, step)
        action_history = actions[np.maximum(action_indices, 0)].copy()
        action_history[action_indices < 0] = observations[0, :2]
        future_indices = np.minimum(np.arange(step, step + self.horizon), len(actions) - 1)
        return dict(obs_hist=self.normalizer.normalize_obs(observations[observation_indices]),
                    act_hist=self.normalizer.normalize_action(action_history),
                    future_actions=self.normalizer.normalize_action(actions[future_indices]),
                    episode_id=np.int64(episode_index), step=np.int64(step))


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--train-episodes", type=int, default=128)
    parser.add_argument("--val-episodes", type=int, default=16)
    parser.add_argument("--test-episodes", type=int, default=16)
    parser.add_argument("--seed", type=int, default=0)
    args = parser.parse_args(argv)
    manifest = make_dataset(**vars(args))
    print(json.dumps(dict(output=str(args.output), counts=manifest["split_counts"],
                          expert_quality=manifest["expert_quality"]), indent=2))


if __name__ == "__main__":
    main()
